{{- if .Values.reacheraven.ai.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reacheraven.name" . }}-ai
  labels:
    app: {{ include "reacheraven.name" . }}
    component: ai
spec:
  replicas: {{ .Values.reacheraven.ai.replicas }}
  selector:
    matchLabels:
      app: {{ include "reacheraven.name" . }}
      component: ai
  template:
    metadata:
      labels:
        app: {{ include "reacheraven.name" . }}
        component: ai
    spec:
      affinity:
        {{- if .Values.global.affinity }}
        {{- toYaml .Values.global.affinity | nindent 8 }}
        {{- end }}
      tolerations:
        {{- if .Values.global.tolerations }}
        {{- toYaml .Values.global.tolerations | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- if .Values.global.nodeSelector }}
        {{- toYaml .Values.global.nodeSelector | nindent 10 }}
        {{- end }}
      {{- if or (.Values.reacheraven.dependencies.redis.install) (.Values.reacheraven.dependencies.rabbitmq.install) }}
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for Redis at {{ include "reacheraven.fullname" . }}-redis-headless:6379..."
              until nc -z {{ include "reacheraven.fullname" . }}-redis-headless 6379; do
                echo "Sleeping for 2s..."
                sleep 2
              done
              echo "Redis is up!"
        - name: wait-for-rabbitmq
          image: curlimages/curl:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for RabbitMQ management API at {{ include "reacheraven.fullname" . }}-rabbitmq-headless:15672..."
              until curl -fsSL http://{{ include "reacheraven.fullname" . }}-rabbitmq-headless:15672/api/version >/dev/null 2>&1; do
                echo "Sleeping for 2s..."
                sleep 2
              done
              echo "RabbitMQ management API is up!"
      {{- end }}
      containers:
        - name: ai
          image: "{{ .Values.reacheraven.ai.image }}:{{ .Values.reacheraven.ai.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: TZ
              value: "{{ .Values.global.timezone | default "UTC" }}"
            - name: AI_EVENTS_EXCHANGE
              value: {{ .Values.reacheraven.ai.env.aiEventsExchange | quote }}
            - name: QUESTION_ROUTING_KEY
              value: {{ .Values.reacheraven.ai.env.questionRoutingKey | quote }}
            - name: AI_QUEUE
              value: {{ .Values.reacheraven.ai.env.aiQueue | quote }}
            - name: OLLAMA_BASE_URL
              value: {{ .Values.reacheraven.ai.env.ollamaBaseUrl | quote }}
            - name: OLLAMA_MODEL
              value: {{ .Values.reacheraven.ai.env.ollamaModel | quote }}
            - name: PORT
              value: {{ .Values.reacheraven.ai.env.port | quote }}
          envFrom:
            - secretRef:
                name: {{ include "reacheraven.fullname" . }}-credentials
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 5
        - name: ollama
          image: "ollama/ollama:latest"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              ollama serve & \
              sleep 5 && \
              ollama pull tinyllama:latest && \
              ollama pull deepseek-r1:1.5b && \
              wait
          ports:
            - containerPort: 11434
          resources:
            limits:
              ephemeral-storage: 6Gi
            requests:
              ephemeral-storage: 6Gi
{{- if .Values.reacheraven.ai.persistence.enabled }}
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ include "reacheraven.name" . }}-ollama-data
{{- end }}
{{- end -}}
