{{- if .Values.reacheraven.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reacheraven.name" . }}-api
  labels:
    app: {{ include "reacheraven.name" . }}
    component: api
spec:
  replicas: {{ .Values.reacheraven.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "reacheraven.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "reacheraven.name" . }}
        component: api
    spec:
      {{- /* afinidades / tolerations omitidas para brevidade */}}
      containers:
        - name: api
          image: "{{ .Values.reacheraven.api.image }}:{{ .Values.reacheraven.api.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JWT_SECRET
              value: {{ .Values.reacheraven.api.env.jwtSecret | quote }}
            - name: JWT_EXPIRATION_HOURS
              value: {{ .Values.reacheraven.api.env.jwtExpirationHours | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.reacheraven.api.env.allowedOrigins | quote }}
            - name: SMTP_HOST
              value: {{ .Values.reacheraven.api.env.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.reacheraven.api.env.smtp.port | quote }}
            - name: SMTP_USERNAME
              value: {{ .Values.reacheraven.api.env.smtp.username | quote }}
            - name: SMTP_PASSWORD
              value: {{ .Values.reacheraven.api.env.smtp.password | quote }}
            - name: DEFAULT_TO_EMAIL
              value: {{ .Values.reacheraven.api.env.smtp.defaultEmail | quote }}
            - name: RABBITMQ_EXCHANGE
              value: {{ .Values.reacheraven.api.env.rabbitmqExchange | quote }}
          envFrom:
            - secretRef:
                name: {{ include "reacheraven.fullname" . }}-credentials
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 5
{{- end }}
