{{- if .Values.reacheraven.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reacheraven.name" . }}-web
  labels:
    app: {{ include "reacheraven.name" . }}
    component: web
spec:
  replicas: {{ .Values.reacheraven.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "reacheraven.name" . }}
      component: web
  template:
    metadata:
      labels:
        app: {{ include "reacheraven.name" . }}
        component: web
    spec:
      affinity: 
        {{- if .Values.global.affinity }}
        {{- toYaml .Values.global.affinity | nindent 6 }}
        {{- end }}
      tolerations:
        {{- if .Values.global.tolerations }}
        {{- toYaml .Values.global.tolerations | nindent 6 }}
        {{- end }}
      nodeSelector:
        {{- if .Values.global.nodeSelector }}
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
        {{- end }}
      containers:
        - name: web
          image: "{{ .Values.reacheraven.web.image }}:{{ .Values.reacheraven.web.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: "{{ .Values.global.timezone | default "UTC" }}"
            - name: REACHERAVEN_API_URL
            {{- if .Values.reacheraven.web.backend.host }}
              value: "{{ .Values.reacheraven.web.backend.host }}"
            {{- else }}
              value: "http://{{ include "reacheraven.fullname" . }}-api:8080"
            {{- end }}

{{- end -}}
             