apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reacheraven.name" . }}-api
  labels:
    app: {{ include "reacheraven.name" . }}
    component: api
spec:
  replicas: {{ .Values.reacheraven.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "reacheraven.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "reacheraven.name" . }}
        component: api
    spec:
      affinity: 
        {{- if .Values.global.affinity }}
        {{- toYaml .Values.global.affinity | nindent 6 }}
        {{- end }}
      tolerations:
        {{- if .Values.global.tolerations }}
        {{- toYaml .Values.global.tolerations | nindent 6 }}
        {{- end }}
      nodeSelector:
        {{- if .Values.global.nodeSelector }}
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
        {{- end }}
      {{- if or .Values.reacheraven.dependencies.postgresql.install .Values.reacheraven.dependencies.redis.install }}
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for PostgreSQL at {{ include "reacheraven.fullname" . }}-postgresql-hl:5432..."
              until nc -z {{ include "reacheraven.fullname" . }}-postgresql-hl 5432; do
                echo "Sleeping for 2s..."
                sleep 2
              done
              echo "PostgreSQL is up!"
        - name: wait-for-redis
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for Redis at {{ include "reacheraven.fullname" . }}-redis-headless:6379..."
              until nc -z {{ include "reacheraven.fullname" . }}-redis-headless 6379; do
                echo "Sleeping for 2s..."
                sleep 2
              done
              echo "Redis is up!"
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.reacheraven.api.image }}:{{ .Values.reacheraven.api.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "{{ .Values.global.timezone | default "UTC" }}"
          envFrom:
            - secretRef:
                name: {{ include "reacheraven.fullname" . }}-credentials