{{- if .Values.reacheraven.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "reacheraven.fullname" . }}-api
  labels:
    app: {{ include "reacheraven.name" . }}
  annotations:
{{ toYaml .Values.reacheraven.api.ingress.annotations | indent 4 }}
spec:
{{- if gt (len .Values.reacheraven.api.ingress.tls) 0 }}
  tls:
{{ toYaml .Values.reacheraven.api.ingress.tls | indent 4 }}
{{- end }}
  rules:
    - host: {{ .Values.reacheraven.api.ingress.host | quote }}
      http:
        paths:
        {{- range .Values.reacheraven.api.ingress.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ include "reacheraven.fullname" $ }}-api
                port:
                  number: 8080
        {{- end }}
{{- end }}
