apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reacheraven.fullname" . }}-credentials
  labels:
    app: {{ include "reacheraven.name" . }}
type: Opaque
data:
  POSTGRES_URL: {{ .Values.reacheraven.dependencies.postgresql.connectionString | b64enc | quote }}
  REDIS_URL: {{ .Values.reacheraven.dependencies.redis.connectionString | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.reacheraven.dependencies.rabbitmq.connectionString | b64enc | quote }}
