apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reacheraven.fullname" . }}-scheduler-secret
type: Opaque
data:
  POSTGRES_URL: {{ .Values.scheduler.env.POSTGRES_URL | b64enc | quote }}
  REDIS_URL: {{ .Values.scheduler.env.REDIS_URL | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.scheduler.env.RABBITMQ_URL | b64enc | quote }}
