apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reacheraven.fullname" . }}-notifier-secret
type: Opaque
data:
  POSTGRES_URL: {{ .Values.notifier.env.POSTGRES_URL | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.notifier.env.RABBITMQ_URL | b64enc | quote }}
