{{- if .Values.reacheraven.ai.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reacheraven.fullname" . }}-ai
  labels:
    app: {{ include "reacheraven.name" . }}
    component: ai
spec:
  type: {{ .Values.reacheraven.ai.service.type }}
  selector:
    app: {{ include "reacheraven.name" . }}
    component: ai
  ports:
    - name: http
      port: 8083
      targetPort: 8083
{{- end -}}
