{{- if .Values.reacheraven.notifier.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reacheraven.fullname" . }}-notifier
  labels:
    app: {{ include "reacheraven.name" . }}
    component: notifier
spec:
  type: {{ .Values.reacheraven.notifier.service.type }}
  selector:
    app: {{ include "reacheraven.name" . }}
    component: notifier
  ports:
    - name: http
      port: 8082
      targetPort: 8082
{{- end -}}