{{- if .Values.reacheraven.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reacheraven.fullname" . }}-api
  labels:
    app: {{ include "reacheraven.name" . }}
    component: api
spec:
  type: {{ .Values.reacheraven.api.service.type }}
  selector:
    app: {{ include "reacheraven.name" . }}
    component: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080

{{- end -}}