{{- if .Values.reacheraven.scheduler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reacheraven.fullname" . }}-scheduler
  labels:
    app: {{ include "reacheraven.name" . }}
    component: scheduler
spec:
  type: {{ .Values.reacheraven.scheduler.service.type }}
  selector:
    app: {{ include "reacheraven.name" . }}
    component: scheduler
  ports:
    - name: http
      port: 8081
      targetPort: 8081

{{- end -}}