apiVersion: v1
kind: Service
metadata:
  name: {{ include "reacheraven.fullname" . }}-web
  labels:
    app: {{ include "reacheraven.name" . }}
    component: web
spec:
  type: {{ .Values.reacheraven.web.service.type }}
  selector:
    app: {{ include "reacheraven.name" . }}
    component: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
