version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:17
    container_name: reacheraven-postgres
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: changeme
      POSTGRESQL_DATABASE: reacheraven
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: reacheraven-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: reacheraven-rabbitmq
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    volumes:
      - rabbitmq_data:/bitnami

  api:
    image: reacheraven/reacheraven-api:v0.2.7
    container_name: reacheraven-api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:changeme@postgres:5432/reacheraven
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://user:bitnami@rabbitmq:5672

  web:
    image: reacheraven/reacheraven-web:v0.1.0
    container_name: reacheraven-web
    ports:
      - "3000:3000"
    depends_on:
      - api

  cron:
    image: reacheraven/reacheraven-cron:v0.1.0
    container_name: reacheraven-cron
    depends_on:
      - api
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:changeme@postgres:5432/reacheraven
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://user:bitnami@rabbitmq:5672

  sender:
    image: reacheraven/reacheraven-sender:v0.1.0
    container_name: reacheraven-sender
    depends_on:
      - api
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:changeme@postgres:5432/reacheraven
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://user:bitnami@rabbitmq:5672

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
