apiVersion: v2
name: reacheraven
description: A Helm chart for deploying the Reacheraven platform
type: application
version: 0.1.0
appVersion: "v0.1.0"

dependencies:
  - name: postgresql
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.11.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 15.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
