apiVersion: v2
name: reacheraven
description: A Helm chart for deploying the Reacheraven platform
type: application
version: 0.4.11 # version of the Helm chart
appVersion: "1.2.7" # version of the Reacheraven platform this chart deploys
icon: https://avatars.githubusercontent.com/u/204897811?s=48&v=4
# Bitnami subchart dependencies (PostgreSQL, Redis, RabbitMQ).
dependencies:
  - name: postgresql
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: reacheraven.dependencies.postgresql.install
  - name: redis
    version: 20.11.4
    repository: https://charts.bitnami.com/bitnami
    condition: reacheraven.dependencies.redis.install
  - name: rabbitmq
    version: 15.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: reacheraven.dependencies.rabbitmq.install
